package pl.lipov.algorytmy

object Repository {

    val floors = listOf(
        // Underground / below ground
        "basement",
        "basement level",
        "lower level",
        "lower ground floor",
        "sub-basement",
        "cellar",
        "underground level",
        "parking level",
        "garage level",
        "B1",
        "B2",
        "B3",
        // Ground-related
        "ground floor",
        "ground level",
        "street level",
        "entry level",
        "lobby level",
        "main floor",
        "reception level",
        // Between floors
        "mezzanine",
        "mezzanine level",
        "intermediate floor",
        "split level",
        "half floor",
        // Numbered floors (American style)
        "first floor",
        "second floor",
        "third floor",
        "fourth floor",
        "fifth floor",
        "sixth floor",
        "seventh floor",
        "eighth floor",
        "ninth floor",
        "tenth floor",
        // Ordinal / generic
        "upper floor",
        "upper level",
        "middle floor",
        "residential floor",
        "office floor",
        "commercial floor",
        // Top / special
        "top floor",
        "top level",
        "penthouse",
        "penthouse level",
        "executive floor",
        "sky level",
        "observation level",
        "roof level",
        "rooftop",
        "terrace level",
        // Technical / restricted
        "service floor",
        "technical floor",
        "mechanical floor",
        "utility level",
        "maintenance level"
    )

    val rooms = listOf(
        // Circulation / communication
        "corridor",
        "hallway",
        "main corridor",
        "side corridor",
        "passageway",
        "walkway",
        "lobby",
        "entrance hall",
        "foyer",
        "atrium",
        "waiting area",
        // Offices & workspaces
        "office",
        "open office",
        "private office",
        "shared office",
        "executive office",
        "coworking room",
        "meeting room",
        "conference room",
        "conference hall",
        "boardroom",
        "training room",
        "seminar room",
        "project room",
        "breakout room",
        "focus room",
        "phone booth",
        "workshop room",
        // Laboratories & research
        "laboratory",
        "laboratory room",
        "wet lab",
        "dry lab",
        "chemical lab",
        "physics lab",
        "biology lab",
        "computer lab",
        "research room",
        "analysis room",
        "clean room",
        "instrument room",
        "specimen room",
        "microscopy room",
        // Education
        "classroom",
        "lecture hall",
        "auditorium",
        "study room",
        "library",
        "reading room",
        "exam room",
        "tutorial room",
        // Residential
        "living room",
        "bedroom",
        "master bedroom",
        "guest room",
        "children's room",
        "kitchen",
        "dining room",
        "bathroom",
        "toilet",
        "shower room",
        "laundry room",
        "pantry",
        "storage room",
        "walk-in closet",
        // Hospitality / hotel
        "hotel room",
        "suite",
        "junior suite",
        "presidential suite",
        "lounge",
        "breakfast room",
        "restaurant hall",
        "bar area",
        "kitchenette",
        // Medical / healthcare
        "examination room",
        "treatment room",
        "operating room",
        "surgery room",
        "intensive care room",
        "patient room",
        "triage room",
        "nurse station",
        "imaging room",
        "MRI room",
        "CT room",
        "X-ray room",
        "pharmacy room",
        "sterilization room",
        // Industrial / technical
        "machine room",
        "server room",
        "data center hall",
        "electrical room",
        "control room",
        "monitoring room",
        "boiler room",
        "pump room",
        "compressor room",
        "generator room",
        "HVAC room",
        "maintenance room",
        "utility room",
        "workshop",
        "tool room",
        // Storage / logistics
        "warehouse",
        "storage hall",
        "cold storage",
        "freezer room",
        "supply room",
        "archive room",
        "document storage",
        "equipment storage",
        "stock room",
        "loading bay",
        "packing room",
        // Retail / commercial
        "shop floor",
        "sales area",
        "showroom",
        "display room",
        "fitting room",
        "cashier area",
        "back office",
        "stockroom",
        // Recreation / sports
        "gym",
        "fitness room",
        "yoga room",
        "dance studio",
        "sports hall",
        "swimming pool hall",
        "sauna room",
        "steam room",
        "game room",
        "recreation room",
        // Cultural / public
        "gallery room",
        "exhibition hall",
        "museum hall",
        "theater hall",
        "cinema room",
        "music room",
        "recording studio",
        "control booth",
        // Security / restricted
        "security room",
        "surveillance room",
        "guard room",
        "safe room",
        "vault room",
        "evidence room",
        // Vehicle-related
        "garage",
        "parking hall",
        "bike storage",
        "charging room",
        // Misc / special
        "multipurpose room",
        "event hall",
        "banquet hall",
        "prayer room",
        "meditation room",
        "server cage",
        "robotics room",
        "simulation room",
        "virtual reality room",
        "green room",
        "backstage area"
    )

    val landmarks = listOf(
        // Structural
        "column",
        "support pillar",
        "load-bearing wall",
        "glass wall",
        "solid wall",
        "large window",
        "skylight",
        "ventilation shaft",
        "ceiling beam",
        "archway",
        "wall recess",
        "doorway",
        "corridor opening",
        "staircase",
        "elevator shaft",
        "elevator door",
        "support beam",
        "ceiling duct",
        "floor drain",
        "fixed railing",
        "fixed partition wall",
        // Infrastructure / technical (but fixed)
        "electrical cabinet",
        "fuse box",
        "HVAC unit",
        "air handling system",
        "sprinkler valve",
        "fire hose cabinet",
        "fire alarm panel",
        "server room door",
        "utility shaft",
        "pipe cluster",
        "fixed ventilation grille",
        // Signage (fixed to structure)
        "exit sign",
        "directional sign",
        "room number plate",
        "wall-mounted map",
        "digital display",
        "warning sign",
        "floor marking",
        // Architectural features
        "indoor garden pit",
        "decorative fountain",
        "sculpture",
        "art installation",
        "large planter"
    )

    val landmarkPositions = listOf(
        "in the middle",
        "in the corner",
        "along the wall",
        "next to the wall",
        "near the entrance",
        "near the exit",
        "at the back of the room",
        "at the front of the room",
        "in the central area",
        "between columns",
        "adjacent to a corridor",
        "beside a column",
        "under the skylight",
        "near the window",
        "near the staircase",
        "near the elevator"
    )

    val userPositions = listOf(
        "in",
        "beginning of",
        "middle of",
        "end of",
        "near entrance of",
        "near exit of",
        "central area of"
    )

    val additionalInfo = listOf(
        "Behind gate is exit ramp for vehicles.",
        "To enter the northeast corridor, you must go through the fire door."
    )
}
